language: ruby
rvm:
  - 2.4.3
before_install: 
  - gem install bundler -v 1.16.1
  - sudo apt-get update -qq
install:
  # mecab
  - wget --no-check-certificate https://github.com/buruzaemon/natto/raw/master/etc/mecab-0.996.tar.gz && tar zxf mecab-0.996.tar.gz
  - pushd mecab-0.996 && ./configure --enable-utf8-only && make && sudo make install && popd
  - sudo ldconfig
  # mecab-ipadic
  - wget --no-check-certificate https://github.com/buruzaemon/natto/raw/master/etc/mecab-ipadic-2.7.0-20070801.tar.gz && tar zxf mecab-ipadic-2.7.0-20070801.tar.gz
  - pushd mecab-ipadic-2.7.0-20070801 && ./configure --with-charset=utf8 && make && sudo make install && popd
  - sudo ldconfig
  # explicitly install ffi and minitest
  - bundle install .bundle
script:
  - bundle exec ruby test/natto2classifier_test.rb
