version: 2
jobs:
  test:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - checkout
      - run: echo 'run test'
      - run: sudo apt-get install ruby-gsl
      - run: gem install bundler:2.2.27
      - run: bundle install
      - run: bundle exec ruby test/natto2classifier_test.rb
workflows:
  version: 2
  test:
    jobs:
      - test
