version: 2
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - checkout
      - run: echo 'run test'
      - run: sudo apt-get update
      - run: sudo apt-get install -y libgsl0-dev
      - run: sudo apt-get install -y mecab libmecab-dev mecab-ipadic-utf8
      - run: export MECAB_PATH=/usr/lib/libmecab.so.2
      - run: gem install bundler:2.2.27
      - run: bundle install
      - run: bundle exec ruby test/natto2classifier_test.rb
workflows:
  version: 2
  test:
    jobs:
      - build
