version: 2
jobs:
  test:
    docker:
      - image: kanayannet/natto2classifier:latest
    steps:
      - checkout
      - run: echo 'run test'
      - run: bundle install
      - run: bundle exec ruby test/natto2classifier_test.rb
workflows:
  version: 2
  test:
    jobs:
      - test
